// Copyright (C) 2026 LayerTwo Labs and contributors
// Licensed under the GNU General Public License v2.0 or later
// SPDX-License-Identifier: GPL-2.0-or-later

import Testing
@testable import ECashWalletMobile

/// Reference values generated by a scratch Rust program that runs the sidechains' OWN derivation code:
/// thunder-rust origin/master (b62658f, v0.18.1) `lib/wallet/bip32.rs` and coinshift-rs (v0.14.8)
/// `lib/wallet/bip32.rs`, copied verbatim, with curve25519-dalek 5.0.0 and frost-ristretto255 rev 0966bd1.
/// Seed = BIP39 "abandon ×11 about", passphrase "".
@Suite struct SidechainCryptoTests {
    private let seed = Bip39Seed.seed(mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about")
    private let thunder = RistrettoSidechainKeyScheme.thunder

    private func hex(_ s: String) -> [UInt8] {
        var out: [UInt8] = []
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!)
            i = j
        }
        return out
    }

    // MARK: Derivation

    @Test func masterKeyMatchesThunderRust() throws {
        let master = try RistrettoBip32.master(seed: seed, biasFix: true)
        #expect(master.scalar == hex("7a0b27459977587c7b1450fb0091d5bae21b1566b0a2cd11ec95298ebec13708"))
        #expect(master.chainCode == hex("7923408dadd3c7b56eed15567707ae5e5dca089de972e07f3b860450e2a3b70e"))
    }

    @Test func accountKeyMatchesThunderRust() throws {
        let account = try thunder.accountKey(seed: seed)
        #expect(account.scalar == hex("a5da3147bb058c653291362ef3a77d94f26b9b84f04a22752c5560c7bcf7140c"))
        #expect(account.chainCode == hex("1460d05097da03f5cc1b777a330923deac86072ff063f5b1a2a9a27f047f7402"))
    }

    @Test(arguments: [
        (UInt32(0), "32d39c31c0c0185b8d80ba6e42be1ed4565c9e249d9530292082edfeaef7f50e",
         "340716be9eea730162132404747f15cde3809e0513ceef5131be81971ec5a131",
         "NKqSr4bQejFbKpd5yLQgWEiMJFx", "s9_NKqSr4bQejFbKpd5yLQgWEiMJFx_eeb2cf"),
        (UInt32(1), "c8152e03025e50d619c0385a5e632c47decec8edacd854792583835222539c09",
         "fe1d62d493cc77443db58985b69d000a3ca63be8ca5a9831253e7a79ed29ff10",
         "2n9MH4oiBFs4sRby3cC8VBaE71Zw", "s9_2n9MH4oiBFs4sRby3cC8VBaE71Zw_ac4e1c"),
        (UInt32(2), "675a1913d837dcc3320dccaec92026124686a43c1b816a6e2846959389d89901",
         "04e9204e08f4136305438ac99dd9d3c317bf6b1dc8e4cc8aa083d794def7ba4b",
         "3Ye7y38EwGcSXVbZgxsR8kMAnhPs", "s9_3Ye7y38EwGcSXVbZgxsR8kMAnhPs_65aa1f"),
    ])
    func thunderAddressesMatchThunderRust(index: UInt32, secret: String, publicKey: String,
                                          address: String, deposit: String) throws {
        let sk = try thunder.signingKey(seed: seed, index: index)
        #expect(sk == hex(secret))
        let pk = try thunder.publicKey(account: thunder.accountPublicKey(seed: seed), index: index)
        #expect(pk == hex(publicKey))
        let addr = SidechainAddress(publicKey: pk)
        #expect(addr.base58 == address)
        #expect(addr.depositString(sidechainNumber: thunder.sidechainNumber) == deposit)
    }

    /// `ChildIndex::from` maps `i ≥ 2^31` to a hardened child.
    @Test func hardenedAddressIndexMatchesThunderRust() throws {
        let sk = try thunder.signingKey(seed: seed, index: 5 | RistrettoBip32.hardenedOffset)
        #expect(sk == hex("37a8b05b7401bb84baeae8936039b01cab3f632dd85ca24a904f1efd29b3be0f"))
    }

    /// coinshift-rs predates the bias fix: same path shape (slot 255), different keys.
    @Test func coinshiftWithoutBiasFixMatchesCoinshiftRust() throws {
        let coinshift = RistrettoSidechainKeyScheme(sidechainNumber: 255, biasFix: false)
        let sk = try coinshift.signingKey(seed: seed, index: 0)
        #expect(sk == hex("2420306741565d1877ac877da3026f7286c1311284a0e5bf4efd299d3c0f3700"))
        let pk = try coinshift.publicKey(account: coinshift.accountPublicKey(seed: seed), index: 0)
        #expect(SidechainAddress(publicKey: pk).base58 == "8STSwPi2qxc4EqUqR2xMSoMiZid")
    }

    @Test func publicDerivationMatchesPrivate() throws {
        let account = try thunder.accountKey(seed: seed)
        let accountPublic = try account.publicKey
        for index in [UInt32(0), 1, 7, 1000] {
            let viaPrivate = try Ristretto255Point.base(thunder.signingKey(account: account, index: index))
            #expect(try thunder.publicKey(account: accountPublic, index: index) == viaPrivate)
        }
    }

    @Test func hardenedPublicDerivationIsRefused() throws {
        let accountPublic = try thunder.accountPublicKey(seed: seed)
        #expect(throws: RistrettoBip32.Error.hardenedPublicDerivation) {
            try thunder.publicKey(account: accountPublic, index: RistrettoBip32.hardenedOffset)
        }
    }

    // MARK: FROST signatures

    /// Fixed nonce k = 42 (test only). frost-ristretto255's own `VerifyingKey::verify` accepted exactly
    /// this signature when it was generated, so matching it byte-for-byte proves the signing formula.
    @Test func deterministicSignatureMatchesFrost() throws {
        let sk = try thunder.signingKey(seed: seed, index: 0)
        let sig = try FrostSchnorr.sign(message: Array("thunder".utf8), secret: sk,
                                        nonce: hex("2a00000000000000000000000000000000000000000000000000000000000000"))
        #expect(sig == hex("e00af9c74d9edb8ebcc160ceec97d531cbd6e2956f9e9162b8e9eda260e82e4318cf14fe08d1277fdc3ff69f054f3e49132af14b02483a8f48cf9ba3f11d5d0c"))
    }

    @Test func signaturesVerifyAndRejectTampering() throws {
        let sk = try thunder.signingKey(seed: seed, index: 1)
        let pk = try Ristretto255Point.base(sk)
        let msg = Array("withdraw".utf8)
        let sig = try FrostSchnorr.sign(message: msg, secret: sk)
        #expect(FrostSchnorr.verify(signature: sig, publicKey: pk, message: msg))
        #expect(!FrostSchnorr.verify(signature: sig, publicKey: pk, message: Array("withdraw!".utf8)))
        var tamperedZ = sig
        tamperedZ[40] ^= 0x01
        #expect(!FrostSchnorr.verify(signature: tamperedZ, publicKey: pk, message: msg))
        var tamperedR = sig
        tamperedR[3] ^= 0x01
        #expect(!FrostSchnorr.verify(signature: tamperedR, publicKey: pk, message: msg))
        let otherPK = try Ristretto255Point.base(thunder.signingKey(seed: seed, index: 2))
        #expect(!FrostSchnorr.verify(signature: sig, publicKey: otherPK, message: msg))
        #expect(!FrostSchnorr.verify(signature: Array(sig.prefix(63)), publicKey: pk, message: msg))
    }

    /// A non-canonical `z` (≥ ℓ) must be rejected even when it's ≡ a valid `z` mod ℓ.
    @Test func nonCanonicalZIsRejected() throws {
        let sk = try thunder.signingKey(seed: seed, index: 0)
        let pk = try Ristretto255Point.base(sk)
        let msg = Array("thunder".utf8)
        let sig = try FrostSchnorr.sign(message: msg, secret: sk)
        // z + ℓ, little-endian, still fits in 32 bytes when z < 2^256 − ℓ (always true for canonical z).
        let order = hex("edd3f55c1a631258d69cf7a2def9de1400000000000000000000000000000010")
        var z = Array(sig[32..<64]), carry = 0
        for i in 0..<32 {
            let sum = Int(z[i]) + Int(order[i]) + carry
            z[i] = UInt8(sum & 0xff)
            carry = sum >> 8
        }
        #expect(!FrostSchnorr.verify(signature: Array(sig[0..<32]) + z, publicKey: pk, message: msg))
    }

}

/// Test helper: `s·G`.
enum Ristretto255Point {
    static func base(_ scalar: [UInt8]) throws -> [UInt8] {
        try RistrettoBip32.PrivateKey(scalar: scalar, chainCode: []).publicKey.point
    }
}
