// Copyright (C) 2026 LayerTwo Labs and contributors
// Licensed under the GNU General Public License v2.0 or later
// SPDX-License-Identifier: GPL-2.0-or-later

import Testing
import Foundation
import Crypto
@testable import ECashWalletMobile

/// The Thunder key stack, each layer pinned to a *published* test vector so correctness doesn't
/// depend on our own implementation:
///   • Base58  → Bitcoin Core's `base58_encode_decode.json`
///   • BIP39   → the canonical "abandon…about" / "TREZOR" seed vector
/// Key derivation and signing themselves are pinned against thunder-rust 0.18's own code in
/// `SidechainCryptoTests` / `ThunderTransaction018Tests`; this suite covers `ThunderKey`'s composition.
/// Swift Testing so it runs on host + Android APK mode.
@Suite struct ThunderKeyTests {

    // MARK: helpers

    private static func bytes(_ hex: String) -> [UInt8] {
        var out = [UInt8](); out.reserveCapacity(hex.count / 2)
        var i = hex.startIndex
        while i < hex.endIndex {
            let j = hex.index(i, offsetBy: 2)
            out.append(UInt8(hex[i..<j], radix: 16)!)
            i = j
        }
        return out
    }
    private static func hex(_ bytes: [UInt8]) -> String {
        bytes.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Base58 (Bitcoin Core vectors)

    @Test func base58EncodeMatchesVectors() {
        let vectors: [(String, String)] = [
            ("", ""),
            ("61", "2g"),
            ("626262", "a3gV"),
            ("636363", "aPEr"),
            ("73696d706c792061206c6f6e6720737472696e67", "2cFupjhnEsSn59qHXstmK2ffpLv2"),
            ("00eb15231dfceb60925886b67d065299925915aeb172c06647", "1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L"),
            ("516b6fcd0f", "ABnLTmg"),
            ("00000000000000000000", "1111111111"),  // leading-zero bytes → '1's
        ]
        for (hexIn, expected) in vectors {
            #expect(Base58.encode(Self.bytes(hexIn)) == expected, "encode \(hexIn)")
            #expect(Base58.decode(expected).map(Self.hex) == hexIn, "decode \(expected)")
        }
    }

    @Test func base58RejectsOutOfAlphabet() {
        #expect(Base58.decode("0OIl") == nil)   // 0, O, I, l are not in the base58 alphabet
    }

    // MARK: - BIP39 seed (canonical vector)

    @Test func bip39SeedMatchesVector() {
        let mnemonic = "abandon abandon abandon abandon abandon abandon "
            + "abandon abandon abandon abandon abandon about"
        let seed = Bip39Seed.seed(mnemonic: mnemonic, passphrase: "TREZOR")
        #expect(Self.hex(seed) == "c55257c360c07c72029aebc1b53c05ed0362ada38ead3e3e9efa3708e5349553"
            + "1f09a6987599d18264c1e1c92f2cf141630c7a3c4ab7c81b2f001698e7463b04")
    }

    // MARK: - ThunderKey (composed derivation)

    private static let testMnemonic = "abandon abandon abandon abandon abandon abandon "
        + "abandon abandon abandon abandon abandon about"

    @Test func thunderKeyShapeIsCorrect() throws {
        let key = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        #expect(key.publicKeyBytes.count == 32)   // compressed ristretto255 point
        #expect(key.address.bytes.count == 20)    // BLAKE3(pubkey)[..20]
        #expect(!key.address.base58.isEmpty)
    }

    @Test func thunderKeyDerivationIsDeterministic() throws {
        let a = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        let b = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        #expect(a.address == b.address)
        #expect(a.publicKeyBytes == b.publicKeyBytes)
    }

    @Test func thunderKeyIndexChangesTheAddress() throws {
        let k0 = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        let k1 = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 1)
        #expect(k0.address != k1.address)
        #expect(k0.publicKeyBytes != k1.publicKeyBytes)
    }

    @Test func thunderAddressBase58RoundTrips() throws {
        let key = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        let parsed = ThunderAddress(base58: key.address.base58)
        #expect(parsed == key.address)
    }

    @Test func thunderKeySignatureVerifies() throws {
        let key = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        let message = Array("thunder tx body".utf8)
        let signature = try key.sign(message)
        #expect(signature.count == 64)   // R ‖ z
        #expect(FrostSchnorr.verify(signature: signature, publicKey: key.publicKeyBytes, message: message))
    }

    /// GOLDEN — the full pipeline (BIP39 → ristretto bip32ish m/43'/1899'/0'/9'/0'/0 → pubkey →
    /// BLAKE3[..20] → base58), generated by thunder-rust v0.18.1's own derivation code.
    @Test func thunderAddressGolden() throws {
        let key = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0)
        #expect(key.address.base58 == "NKqSr4bQejFbKpd5yLQgWEiMJFx")
    }

    /// The mainchain deposit form: `s9_{base58}_{sha256("s9_{base58}_")[..3] hex}`
    /// (`address.rs::format_for_deposit`, `THIS_SIDECHAIN == 9`). Checksum recomputed independently.
    @Test func depositStringHasSidechain9PrefixAndSha256Checksum() throws {
        let address = try ThunderKey.derive(mnemonic: Self.testMnemonic, index: 0).address
        let deposit = address.depositString(sidechainNumber: RistrettoSidechainKeyScheme.thunder.sidechainNumber)
        let prefix = "s9_\(address.base58)_"
        #expect(deposit.hasPrefix(prefix))
        let digest = Array(SHA256.hash(data: Data(prefix.utf8)))
        let checksum = digest.prefix(3).map { String(format: "%02x", $0) }.joined()
        #expect(deposit == prefix + checksum)   // 6 hex chars of the first 3 sha256 bytes
        #expect(RistrettoSidechainKeyScheme.thunder.sidechainNumber == 9)
    }
}
